mysite/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path("polls/", include("polls.urls")),
]

polls/urls.py
from django.urls import path

from . import views


app_name = 'polls'
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

polls/views.py
from django.utils import timezone
from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.all()
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("pub_date")[
            :5
        ]

class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "PICK SOMETHING",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))
    
# def index(request):
#     latest_question_list = Question.objects.order_by("-pub_date")[:5]
#     context = {"latest_question_list": latest_question_list}
#     return render(request, "polls/index.html", context)

# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/detail.html', {'question': question})

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "polls/results.html", {"question": question})

polls/templates/polls/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Django Poll</title>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Oswald:wght@200..700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Metal+Mania&display=swap" rel="stylesheet">
    {% comment %} <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"/> {% endcomment %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
  </head>

  <body>

    <header>
      <h1><a href={% url 'polls:index' %} title="Startpagina">Django Poll</a></h1>
    </header>

    <main>
      {% block content %}
      {% endblock %}
    </main>

  </body>

</html>

polls/templates/polls/detail.html
<!-- prettier-ignore -->
{% extends 'polls/base.html' %}

{% block content %}
<div class="detail">
    <h2 class='template-title'>DETAIL</h2>
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <h1><span class="q-number">Q{{ question.pk }}:</span> {{ question.question_text }}</h1>
        
        {% if error_message %}<p class="error-msg"><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
        
        <label for="choice{{ forloop.counter }}">
            {{ choice.choice_text }}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        </label>
        {% endfor %}
        <input type="submit" value="Vote">
    </form>
</div>
{% endblock %}
 

polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content %}
<div class="index">
    <h2 class='template-title'>INDEX</h2>
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            {% comment %} <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li> {% endcomment %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.pk}}. {{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
</div>
{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block content %}
<div class="result">
    <h2 class='template-title'>RESULTS</h2>
    <h1><span class="q-number">Q{{ question.pk }}:</span> {{ question.question_text }}</h1>
    {% comment %} <h1>{{ question.question_text }}</h1> {% endcomment %}

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}<span class='votes-amount'>{{ choice.votes }} vote{{ choice.votes|pluralize }}</span></li>
    {% endfor %}
    </ul>

    <a class='vote-again-link' href="{% url 'polls:detail' question.id %}">Vote again?</a>
</div>
{% endblock %}